server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

appConfig:
  musicLocation: /Users/deepak.barr/hackathon/codeSpace/music
  musicMetaLocation: /Users/deepak.barr/hackathon/codeSpace/TunesBot/src/main/resources/musicfile.json
  adsLocation: /Users/deepak.barr/hackathon/codeSpace/TunesBot/src/main/resources/ad
